apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-binding
  namespace: portfolio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-runner-role
subjects:
- kind: ServiceAccount
  name: arc-runner-sa
  namespace: portfolio
