apiVersion: v1
kind: Service
metadata:
  name: portfolio-nextjs
  namespace: portfolio
spec:
  selector:
    app: portfolio-nextjs
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP
